### ISSUE TITLE
Nested KeyboardTrackingView causing weird behavior

### ISSUE THREAD

**Issue by diegolmello** [wix/react-native-ui-lib#1051]
**Describe the bug**
We have nested KeyboardTrackingViews on our app and it causes a blank space below the TextInput.

**To Reproduce**
1. Checkout this reproducible repo https://github.com/diegolmello/TrackingViewDemo
2. Tap on `Open new tracking view`
3. Navigate back
4. Open the TextInput from the first view
5. Blank space will be shown

**Expected behavior**
There's no blank space

**Code snippet**
https://github.com/diegolmello/TrackingViewDemo

**Screenshots**
![Nov-27-2020 17-35-13](https://user-images.githubusercontent.com/804994/100482991-fcf54880-30d6-11eb-8d25-8e45325265e5.gif)
Check how the TextInput is correctly styled until I navigate back to the first screen on the gif above.

**Device (please complete the following information):**
 - Device: Any iOS (simulator or not)
 - OS: Mac

**Additional context**
I've been debugging this issue for two days, but I'm afraid I'm not having any progress.
It looks like `ObservingInputAccessoryViewTemp` isn't uninstantiated when the second TextInput unmounts.
Set a breakpoint [here](https://github.com/wix/react-native-ui-lib/blob/master/lib/ios/reactnativeuilib/keyboardtrackingview/ObservingInputAccessoryViewTemp.m#L99) and [here](https://github.com/wix/react-native-ui-lib/blob/master/lib/ios/reactnativeuilib/keyboardtrackingview/KeyboardTrackingViewTempManager.m#L337)

**Comment by mendyEdri** [comment]
Hi @diegolmello, thanks for your bug report!

It seems like it's related to `react-navigation` way of implementation.
Using your demo code with other navigation (`react-native-navigation`) won't reproduce the issue and works as expected. 

I would suggests you try to check if there is a component render below your KeyboardTrackingView / Some left-out constraint. 
(Otherwise, it would act the same even without the push and pop screens)

Let me know, and i'm here if you have any question
