### ISSUE TITLE
WizardStep color being overridden by StatesConfig

### ISSUE THREAD

**Issue by stanica** [wix/react-native-ui-lib#1180]
Line 81 of WizardStep.js

`return {...config, ...props, ...activeConfig};`

causes the `color` prop of WizardStep to be overridden by the colors defined in WizardStates.js

**Comment by M-i-k-e-l** [comment]
Hi @stanica,
If you mean that it takes the `activeConfig` then it's "by design", an active step will always have the active UI.
We're still working on the docs for this component (some infra work on the docs is required for it to be readable), but you can see in [here](https://github.com/wix/react-native-ui-lib/pull/1140/files#diff-b0cb9d155ee52b050ac717e644e26cba1481c4f4c98ac45f096ddd0a40087d86R19-R23) how the `activeConfig` can be changed (look in the said PR on how to change the other steps' config):
```
ThemeManager.setComponentTheme('Wizard', (props, context) => {
   const containerStyle = {width, marginLeft, paddingVertical, paddingHorizontal};
   const activeConfig = {color: activeColor, circleColor: activeColor};
   return {containerStyle, activeConfig};
 };
```

Please let me know if that's not what you meant or if you need further help.

**Comment by stanica** [comment]
That worked, thanks!
