### ISSUE TITLE
MaskedInput  programmed cleaning

### ISSUE THREAD

**Issue by URVL** [wix/react-native-ui-lib#1231]
what is the best way to programmatically clear the input in MaskedInput ?
(MaskedInput wrapper  - functional component) @ethanshar

**Comment by URVL** [comment]
Hi, is there anyone here?  @ethanshar @Inbal-Tish

**Comment by ethanshar** [comment]
Hey @URVL 
I see that we don't forward ref to the inner TextInput. 
So unfortunately you can't pass a ref and use the `clear` method. 

Since you have control over the value of the masked input, you can manually clear it by connecting it to a state. 
Anyway, I'll take a look and fix the ref forwarding

**Comment by URVL** [comment]
> Anyway, I'll take a look and fix the ref forwarding

Thanks for the answer) I'm looking forward to it

**Comment by URVL** [comment]
@ethanshar hello when will this option be available in a standalone package react-native-ui-lib, version 5.22.0 doesn't have it yet (

**Comment by ethanshar** [comment]
Unfortunately, 5.22.0 was released before this change was merged. 
Therefore it will be available on our next version -> 5.23.0

You can experiment with the non-official version by installing `react-native-ui-lib@snapshot`
