### ISSUE TITLE
Card : Shadow is still enabled when defining a containerStyle in ThemeManager

### ISSUE THREAD

**Issue by RaphBlanchet** [wix/react-native-ui-lib#2007]
## Description

When defining a `containerStyle` for a Card in the `ThemeManager`, the shadow is still displayed even when defining `enableShadow: false`. This bug doesn't happen when defining these properties on the component (i.e `<Card enableShadow={false} containerStyle={{ backgroundColor: 'gray' }}>`

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce

1. Define a new `Component Theme` for a Card
2. Define `enableShadow` to `false`
3. Define a `containerStyle` (i.e `containerStyle: { backgroundColor: 'gray' }`)
4. Add a `Card` component to your `View`

#### Expected behavior

The Card's shadow shouldn't be enabled

#### Actual behavior

The Card's shadow is enabled

## More Info

The shadow can still be "disabled" by defining a transparent `shadowColor` in `containerStyle`

### Code snippet

```
ThemeManager.setComponentTheme('Card', (props, context) => {
    return {
        enableShadow: false,
        containerStyle: { backgroundColor: Colors.cardBackground },
        elevation: 0
    }
})

```

### Screenshots/Video

![Screen Shot 2022-04-24 at 1 00 12 PM](https://user-images.githubusercontent.com/11820540/164987809-441147a9-eccb-4fe3-9283-06ecae7159c4.png)

### Environment

- React Native: `0.66.4`
- React Native UI Lib: `6.13.3`

### Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by M-i-k-e-l** [comment]
Hi @RaphBlanchet,

The problem occurs because we have `defaultProps` for `Card` that sets `enableShadow: true`.
You can solve it by using `setComponentForcedTheme` instead of `setComponentTheme`, but then it will not be possible to change the props sent in the component (it **forces** these props). So **all** your Cards will not have shadows.

Please let me know if that solves your problem.
