### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by mnlbox** [wix/react-native-ui-lib#229]
I see a lot of old PR and Issues. Is this library still maintained?
As @rotemmiz told in https://github.com/wix/react-native-interactable/issues/227 `react-native-interactable` is not being maintain by Wix team. Now we can't use `react-native-ui-lib` because of #223 , #224 and some related issue that fixed in https://github.com/wix/react-native-interactable/pull/211 PR and wait for merge.
Are you any plan to remove `react-native-interactable` from `react-native-ui-lib` dependencies or Wix don't want to maintained `react-native-ui-lib` too?

I asked it because without https://github.com/wix/react-native-interactable/pull/211 now `react-native-ui-lib` isn't compile and useless in action.

**/CC:** @ethanshar, @Inbal-Tish, @artald

**Comment by Inbal-Tish** [comment]
'react-native-ui-lib' library is maintained constantly and we are trying to address all issues and PR when our schedule allows us to do so. Since uilib is not using `react-native-interactable` internally, this dependency will be removed soon. Hope that will resolve the issue, though issue  #224 is a react-native issue and not a uilib one. In any case, there shouldn't be a problem to compile uilib at its current state, but if you need a specific assistance please open an issue with the relevant details.

**Comment by Inbal-Tish** [comment]
'react-native-interactable' was removed as a dependency. Please check if it resolved your issue.
