### ISSUE TITLE
Toast component appears behind Dialog and Dialog's overlay

### ISSUE THREAD

**Issue by allynsweet** [wix/react-native-ui-lib#2373]
## Description
The Toast component appears behind the Dialog and overlay.

### Related to

- [X] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce
1. Open a Dialog component.
2. Trigger a Toast component to appear.
3. The Toast component will appear behind the Dialog and overlay.

#### Expected behavior
Since Toast components are typically used for notifications, the Toast component should always appear over any existing Dialogs.

#### Actual behavior
The Toast component appears behind the Dialog and its overlay.

#### What I've tried
I adjusted the zIndex on the Toast to be at the top, as well as adjusted the ordering of components to ensure the Toast was the top layer, but the issue has persisted.

### Screenshots/Video
![Screen Shot 2022-12-13 at 8 31 03 PM](https://user-images.githubusercontent.com/10257776/207483164-61a1f7ce-f473-4ad2-a3de-0ac31245f0cf.png)

### Environment

- React Native version: 0.69.4
- React Native UI Lib version: 6.24.0

**Comment by RaphBlanchet** [comment]
Hey @allynsweet, I encountered the same problem as you, but in my case, I am using the package `react-native-toast-message` to display my toasts, which is basically the same API.

Nonetheless, I temporarily fixed the problem by creating this patch file, which added a new prop to `Dialog`: `modalChildren`. This prop lets me add anything inside the `Modal` component, right after the rendering of the Dialog.

[react-native-ui-lib+6.27.3.patch](https://github.com/wix/react-native-ui-lib/files/10367883/react-native-ui-lib%2B6.27.3.patch)

In order to patch the package, you will need `patch-package`: https://www.npmjs.com/package/patch-package (And you might need to rename the file to use `6.24.0` instead)

Once patched, I am using it like this : 
```
<Dialog 
    modalChildren={<Toast ... />}
>
    ...
</Dialog>
```

This is not the cleanest, and I don't know if this would pass this lib's code standard (hence why I am not PRing this) but at least this is fixing the bug while the team works on it!

Hope it helps 😃

**Comment by allynsweet** [comment]
Hey @RaphBlanchet, thanks for the workaround! I'll try it out this week and report back, it seems that should be a good solution in the meantime.
