### ISSUE TITLE
 text10, text20, text30 - Font size is different in Android & iOS

### ISSUE THREAD

**Issue by mkharibalaji** [wix/react-native-ui-lib#30]
Hi,
   The font size is bit bigger in Android compared to iOS for the following font sizes text10,20,30 while others seem to remain almost the same in typography.It would be great if this issue is fixed.

**Comment by ethanshar** [comment]
Hey @mkharibalaji , 
It's not exactly an issue. these typographies were defined with the help of a designer and meant to be platform specific. meaning we're treating on Android and iOS differently in some aspects since they are different (: 
you can see the presets here:
https://github.com/wix/react-native-ui-lib/blob/master/src/style/typography.js
it's actually the same for text10,20,30 but different in other presets.

Anyway, I do agree some people wouldn't want that and for that I provided the ability to override typographies presets as follow: 

```
Typography.loadTypographies({
  text10: {
    fontSize: 64,
  },
  text20: {
    fontSize: 50,
  },
});
```

You can also just override part of a preset with spread operator
```
Typography.loadTypographies({
  text10: {
    ...Typography.text10,
    fontSize: 64,
  },
});
```

Hopes this helps
