### ISSUE TITLE
Can't set the picker's modal background color.

### ISSUE THREAD

**Issue by king960** [wix/react-native-ui-lib#3111]
## Description
It is not possible to change the picker's modal colour, because in PickerItemsList you use
'$backgroundDefault' that always falls back into white colour.
`<View bg-$backgroundDefault style={wrapperContainerStyle} useSafeArea={useSafeArea}>`

### Related to

- [x] Components
- [ ] Demo
- [ ] Docs
- [ ] Typings

### Steps to reproduce
1. Create a picker
2. Open the picker and see that the background is white.

#### Expected behavior
If there's an option to specifically set the overlay color, then it should work.
#### Actual behavior
`pickerModalProps={{overlayBackgroundColor: 'red'}}` has no effect

## More Info

You can confirm that the overlayBackgroundColor will work if you do:
`Colors.loadSchemes({
    light: {
        $backgroundDefault: 'transparent',
    },
    dark: {
        $backgroundDefault: 'transparent'
    }
});`

### Code snippet

` <Picker
            pickerModalProps={{overlayBackgroundColor: 'red'}}
            label={'test'}
            value={'test}
            onChange={(value) => {}}
            items={{label: 'test', value: ''}}
        />`

### Environment

- React Native version: 0.74.1
- React Native UI Lib version: 7.23.2

### Affected platforms

- [ ] Android
- [x] iOS
- [ ] Web

**Comment by adids1221** [comment]
Hi @king960 ,
First of all it's isn't a bug, the `Modal` overlay background is visible when using Dialog mode.
When using `Picker` as `Modal` there is no overlay background since the `Modal` covers all the screen.
What you asked for is a feature, Iv'e created this [PR](https://github.com/wix/react-native-ui-lib/pull/3214) to add `background` color prop to the Picker which will override the `PickerItemList` background color.
