### ISSUE TITLE
[TASK] Add more docs

### ISSUE THREAD

**Issue by ethanshar** [wix/react-native-ui-lib#8]
In order to understand more how the UILib works, we need to add better documentation.

**Comment by ethanshar** [comment]
Guys, please comment here with what you think is missing? 
Which components are not covered? 
What else you would like to know? 

Thanks!

**Comment by xsokev** [comment]
Hi Ethan. Thanks for creating this library. I much prefer your implementation to the many others that exist. I was developing my own implementation before I found react-native-ui-lib and have since stopped development in favor of yours. 
I wanted to contribute here in any way I can because it has already been useful for me. I noticed the documentation is limited so I started putting together some docs from your codebase to help me as I continue to use react-native-ui-lib. I am using GitBook as it appears to be an easy solution that is commonly used. 
The link is: [https://xsokev.gitbooks.io/react-native-uilib/](https://xsokev.gitbooks.io/react-native-uilib/)

I tried using the current docs you have but failed to get anything to load due to some babel/webpack issues so I don't know how much you have already done. I will continue hacking on GitBook and hopefully they can be useful to others until you have completed your official docs. Thanks again!

**Comment by cheuk3** [comment]
Hi Xsodev, is the source code of expo demo available?

Thanks!

**Comment by xsokev** [comment]
I will check it into a GitHub repo and let you know when it's done.

**Comment by cheuk3** [comment]
cool man, many thanks!

**Comment by xsokev** [comment]
np, it's checked in. (https://github.com/xsokev/react-native-ui-lib-expo)
Most everything is the same. I just used react-navigation instead of react-native-navigation.

**Comment by cheuk3** [comment]
thanks xsokev, it help me a lot!

**Comment by ethanshar** [comment]
@xsokev WOW, Amazing! 
this helps a lot. 
I would like to dive more into what you did during this week and see how we can improve it and add more content.

Thanks for your contribution (:

**Comment by ethanshar** [comment]
I've got inspired to put some effort on the docs site. 
And using the Great [Gatsby](https://www.gatsbyjs.org/) I've create a quick draft of a nice docs site.
check it out here:
https://wix.github.io/react-native-ui-lib/

I will keep work on it over time and improve it, the good thing about it is that it auto generates the site according to the code (based on react-docgen), so maintaining it should be very easy (:

**Comment by leoxiaoping** [comment]
Giving a overview demo in android apk is especially important when the library has no demo on Expo.
Otherwise, the user is easy to give up at the beginning stage. I think that's why this libray hasn't many stars.

**Comment by ethanshar** [comment]
Hey @leoxiaoping 
We have problem with make our demo app work on Expo because we're using react-native-navigation which doesn't work with Expo. 
If you have a way to contribute and make the app work on Expo it will be highly appreciated 🙏

**Comment by leoxiaoping** [comment]
> Hey @leoxiaoping
> We have problem with make our demo app work on Expo because we're using react-native-navigation which doesn't work with Expo.
> If you have a way to contribute and make the app work on Expo it will be highly appreciated 🙏

Because of  the native components and 'eact-native-navigation' which contains native module,It is not possible to make demo work with Expo.
So I suggest publish an Android apk install file with new release.This is the current lowest cost option.
