### ISSUE TITLE
KeyboardAwareScrollView not working correctly with TextArea or multiline Textfields on iOS

### ISSUE THREAD

**Issue by Jeancpdamke** [wix/react-native-ui-lib#841]
If there is a Textfield with the "multiline" attribute set to true or a TextArea inside a KeyboardAwareScrollView, the Scrollview doesn't consider the keyboard space for these elements.

Steps to reproduce:

Run the Demo app with react-native run-ios.
Replace the ScrollView on line 70 of demo/src/screens/componentScreens/TextFieldScreen/InputsScreen.js for a KeyboardAwareScrollView (imported from this library).
The regular TextFields will adjust to the remaining height of the screen when the keyboard is opened after click, while the TextArea and TextField with "multiline={true}" won't.

**Comment by M-i-k-e-l** [comment]
Hi @Jeancpdamke,
I am not sure what you mean exactly, do you mean that the KeyboardAwareScrollView does not auto-scroll when you go to the next line or actually that something is hidden from view?

**Comment by Jeancpdamke** [comment]
When you focus on a TextField with `multiline={true}`, if the keyboard opens and overlays the input, the input will stay hidden under the keyboard. The expected behaviour would be to have the KeyboardAwareScrollView detect this and scroll up, making the TextInput visible, as it happens with a regular TextInput.

**Comment by M-i-k-e-l** [comment]
From what I've seen we're not getting the `onScroll` event when `multiline={true}`.
I'm not entirely sure, but I think the reason is [this code](https://github.com/facebook/react-native/blob/master/Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m#L44-L73) (RN's TextInput). It seems they are blocking the `onScroll` event (maybe `RCTDirectEventBlock` has different behaviour on iOS and Android).
Please note that the code is for the multiline variant (there is [another file](https://github.com/facebook/react-native/blob/master/Libraries/Text/TextInput/Singleline/RCTSinglelineTextInputView.m) for singleline).

I've found this also happens on RN's `KeyboardAvoidingView` ([see here](https://github.com/facebook/react-native/issues/16826)), it seems that the best solution ATM is to set `scrollEnabled={false}` to the `TextField` (or `InputText`) ([see here](https://github.com/facebook/react-native/issues/16826#issuecomment-511745933)).
There are other workarounds for this at that page (if you can't disabled the scroll), but I think it's an underline RN bug that causes it to fail.
@Jeancpdamke, please let me know if you can use the workaround I've suggested.
@ethanshar, what do you think, should we wait for the underline issue to be solved or try to find a solution (I fear that it will complicate the code a lot for a relatively small bug)?

**Comment by ethanshar** [comment]
@M-i-k-e-l Let's wait for the issue to be resolved and revisit it in the future.

**Comment by Jeancpdamke** [comment]
@M-i-k-e-l using `scrollEnabled={false}` does not solve my case, because I need the scroll to be enabled. What I did to minimize the occurence of the issue is conditionally set the scrollEnable as `scrollEnabled={value.length > 150}`. (150 is the number of characters that start to overflow the input, and thus need the scroll to be active again).

**Comment by nickpagee** [comment]
has anyone been able to confirm if the underlying RN issue has been solved?
