### ISSUE TITLE
Expo App and Expo Snack aren't working

### ISSUE THREAD

**Issue by olhapi** [wix/react-native-ui-lib#866]
Here's what error expo snack is showing:
![image](https://user-images.githubusercontent.com/4780263/88492767-ba4f2280-cfb5-11ea-8fef-d00efd503449.png)

Expo app just shows expo logo forever.

As was mentioned in another issue #8 that's due to react-native-navigation doesn't work with expo. May be a good idea to temporarily remove that Expo app/snack banner from the homepage and provide APK of demo app as was proposed.

I'm just found out about this UI kit and think that it's awesome and underestimated.

**Comment by tomByrer** [comment]
https://github.com/wix/react-native-navigation/issues/6382

**Comment by SrBrahma** [comment]
Also happening here, can't test this lib via Expo.

**Comment by kyungjoongo-ailab** [comment]
same
Doesn't run at the expo.

**Comment by nickpagee** [comment]
same issue can't run the snack , breaks in lots of places even after downloading and installing all packages – can't wait to try this though !

**Comment by ethanshar** [comment]
Please try again. 
I added the missing dependency (react-native-animatable) 

Try running the snack on your device. I just tried it on my iPhone and it worked. 

Noticed that some components depend on our native code, and since our native code is not yet part of expo it won't work as expected. 
However, they can be tested by running our demo app locally (without expo) 
https://wix.github.io/react-native-ui-lib/getting-started/setup (check at the bottom, the section on our Demo App)

**Comment by nickpagee** [comment]
amazing! really sincerely appreciate this Ethan
does this mean the Keyboard Input component will work if run locally
without Expo? That's the one we're super keen to incorporate
–thanks again for this, 🙌🍻

**Comment by murbanowicz** [comment]
hat's still true. Came across your library and unfortunately cannot try it because of the broken Expo app/snack :(

**Comment by ethanshar** [comment]
Hi @murbanowicz, 
What are you experiencing exactly? 
What error message do you get? 

Also, are you trying on iPhone or an Android device?

**Comment by murbanowicz** [comment]
Random red errors as above.
Android phone with the latest Expo client.

**Comment by dmg46664** [comment]
@ethanshar Running into a problem where Drawers resets Expo and I don't see it on Android.
Given the apparent issues perhaps it's better to tell people to install locally on the README instead of hitting issues? Or alternatively marking examples that don't work inside the app.

Anyway, cheers for all your great work 😄

**Comment by saravanakumargn** [comment]
Please try this React Native Components Explorer App to see the behavior of the components.

Android: https://play.google.com/store/apps/details?id=org.saravanakumar.reactnativecomponentsexplorer

iOS: https://apps.apple.com/us/app/react-native-components/id1333539401
